### ISSUE TITLE
"Tap to approve" function support?

### ISSUE THREAD

**Issue by dmikushin** [AndreyRusyaev/simpleauthenticator#1]
Hi @AndreyRusyaev , thank you for this cool app!

The most often used (and the most annoying) function of Microsoft Authenticator is "Tap to approve". I mean the app screen, where I have to interactively tap "Approve" popup menu, instead of entering the pin code. I think this function is not a part of an RFC, as long as it requires push notifications, rather than just passively entering the pin code. Therefore, I'm not surprised that most of authenticators do not implement it. But if you have to, how would you implement it using your favorite tools?

**Comment by AndreyRusyaev** [comment]
Hi, @dmikushin 

I don't think that console desktop app can/could support that. 
But as a system design exercise:
* Have a preagreed auth-endpoint for each registered service in authenticator App with pre-agreed protocol that expects a callback with request Id and PIN/Token (time/hmac-based). 
* Send a push notification with service name and request id,
* Authenticator app after receiving such notification could make a callback to pre-agreed service endpoint with extracted request id and current generated PIN/token,
* Authentication request completes successfully.

**Comment by dmikushin** [comment]
@AndreyRusyaev , could an authentication app not officially endorsed by Microsoft in principle receive their push notifications? I think this is the main question to answer, before engineering a prototype.

**Comment by AndreyRusyaev** [comment]
Do you mean receive push notifications intended for Microsoft authenticator app? No, I don't think you can. 
For the scheme I suggest you need to register your target authenticator app on the authentication server that will implement it.
Probably something similar possible for Microsoft authentication server, but for that you need to ask them - do they support 3rd party authentication apps and how to implement that support if they do.
