### ISSUE TITLE
Great Code - Question about Base32 vs Base64

### ISSUE THREAD

**Issue by drewid** [AndreyRusyaev/simpleauthenticator#2]
Hello - great code and I have been able to successfully use it.

Question -> how do you know when to use Base32 vs Base64?

**Comment by drewid** [comment]
Actually, it looks like Base32 is being used everywhere and Base64 is not really in use?  Good to have the capability though.

**Comment by AndreyRusyaev** [comment]
Yep, base32 is generally accepted as default case for key exchange, but it's not standardized in any way. 
Sometimes base64 could be more convenient due to less characters required for encoding of the shared key.
